# Schedule

## Lecture 1: Visualisation

### Week 8

February 22, 2021 - February 26, 2021 

### Preparation

Before class you should have

- installed the software
- cloned the repo from\url{https://github.com/misjamikkers/Rprogramming21_student} on your computer
- finished datacamp course "Introduction to the Tidyverse"

### In class

In class we will go through the notebook of lecture 1



## Lecture 2: Data wrangling 1

### Week 9

March 1, 2021 - March 5, 2021

### Preparation

Before class you should have

- finished datacamp course "Introduction to R"

### In class

In class we will go through the notebook of lecture 2


## Lecture 3: Data wrangling 2

### Week 10

March 8, 2021 - March 12, 2021


### Preparation

- downloaded some data
- made your own notebook with some data wrangling and a plot

The aim of this preparation is to practice  with the skills required until now. This should be a good preparation for the exam with respect to the basis programming skills. 

### In class 

In class we will have some time to answer your questions with respect to your prepared notebook.

Furthermore, we will go through the notebook of lecture 3.


## Lecture 4: Functions and R Markdown


### Week 11

March 15, 2021 - March 19 2021

### Preparation

For a super compact introduction to R Markdown, watch [This 1-minute video](https://vimeo.com/178485416).

Got that? No worries, we go over it step by step in the R notebooks.

“A reproducible workflow” by Ignasi Bartomeus and Francisco Rodríguez-Sánchez (https://youtu.be/s3JldKoA0zw) is a 2-min video that looks artistic but also shows very common and practical problems in data analysis, and how R markdown solves these.

### In class

In class we will go through the notebooks of lecture 4.
First is the functions notebook, then the R Markdown notebook (that includes a Markdown refresher notebook as exercise). 


## Lecture 5: Generating data and some statistics


### Week 12

March 22, 2021 - March 26, 2021

### Preparation

Nothing.

### In class

In class we will go through the notebook of lecture 5.


